name: CI

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - "**.md"
    tags:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: deno lint

  fmt:
    runs-on: ubuntu-latest
    - uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - run: deno fmt --check
