name: CI

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - "**.md"
    tags:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: deno lint

  fmt:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: deno fmt --check

  release:
    runs-on: ubuntu-latest
    needs: fmt
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
